### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by matt2000** [trustedanalytics/h2o-scoring-engine-base#3]
If it is, I'll continue to submit pull requests as I add functionality.

**Comment by dpuzio** [comment]
Yes, it is maintained. Thank you for your contribution. I'll review your changes and come back with a feedback in a few days.

**Comment by matt2000** [comment]
Thanks. I'm aware of the unfortunate fact that my contributions come without unit tests. I'd appreciate any assistance you can provide there. E.g., It's not clear to me if I should include another test model like h2o-one-model-test-lib.jar, or if I should create another test model for demonstrating the JSON object functionality.
